apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 3tirewebapp-dev

resources:
  - namespace.yaml
  - secret.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml

commonAnnotations:
  app.kubernetes.io/version: "1.0"

images:
  - name: itsbaivab/frontend
    newTag: v2
  - name: itsbaivab/backend
    newTag: latest
  - name: postgres
    newTag: "15"

replicas:
  - name: frontend
    count: 2
  - name: backend
    count: 2
  - name: postgres
    count: 1
