apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-from-kv
  namespace: 3tirewebapp-dev
type: Opaque
stringData:
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
